server:
  port: 8769

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/891760188/springcloudbook/
          searchPaths: SpringcloudConfig/respo
          username:
          password:
      label: master


#        native:
#          search-locations: classpath:/shared
#  profiles:
#     ### 通过spring.profiles.active=native来配置从本地读取配置，读取配的路径为classpath下的hared目录
#     active: native
  application:
    name: config-server




